services:
  db:
    image: postgres:15-alpine
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: tgbot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_URL: "host=${DB_HOST} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"

volumes:
  pg_data:
